version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # Location of requirements.txt or pyproject.toml
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/docker" # Location of Dockerfile
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/" # GitHub Actions workflows
    schedule:
      interval: "weekly"
