# Generated by Django 5.0 on 2024-01-28 06:37

import django.db.models.deletion
import itgdb_site.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=itgdb_site.models.get_simfilemedia_storage, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('release_date', models.DateTimeField()),
                ('banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_packs', to='itgdb_site.imagefile')),
                ('tags', models.ManyToManyField(blank=True, to='itgdb_site.tag')),
            ],
        ),
        migrations.AddField(
            model_name='imagefile',
            name='pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itgdb_site.pack'),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(max_length=500)),
                ('artist', models.CharField(max_length=255)),
                ('title_translit', models.CharField(max_length=500)),
                ('subtitle_translit', models.CharField(max_length=500)),
                ('artist_translit', models.CharField(max_length=255)),
                ('credit', models.CharField(max_length=255)),
                ('min_bpm', models.FloatField()),
                ('max_bpm', models.FloatField()),
                ('min_display_bpm', models.FloatField(blank=True, null=True)),
                ('max_display_bpm', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField()),
                ('release_date', models.DateTimeField()),
                ('simfile', models.FileField(storage=itgdb_site.models.get_simfiles_storage, upload_to='')),
                ('banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_songs', to='itgdb_site.imagefile')),
                ('bg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bg_songs', to='itgdb_site.imagefile')),
                ('cdtitle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdtitle_songs', to='itgdb_site.imagefile')),
                ('jacket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jacket_songs', to='itgdb_site.imagefile')),
                ('pack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itgdb_site.pack')),
            ],
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps_type', models.SmallIntegerField(choices=[(1, 'dance-single'), (2, 'dance-double')])),
                ('difficulty', models.SmallIntegerField(choices=[(0, 'beginner'), (1, 'easy'), (2, 'medium'), (3, 'hard'), (4, 'challenge'), (5, 'edit')])),
                ('meter', models.IntegerField()),
                ('credit', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('chart_name', models.CharField(blank=True, max_length=255, null=True)),
                ('chart_hash', models.CharField(max_length=40)),
                ('objects_count', models.PositiveIntegerField()),
                ('steps_count', models.PositiveIntegerField()),
                ('combo_count', models.PositiveIntegerField()),
                ('jumps_count', models.PositiveIntegerField()),
                ('mines_count', models.PositiveIntegerField()),
                ('hands_count', models.PositiveIntegerField()),
                ('holds_count', models.PositiveIntegerField()),
                ('rolls_count', models.PositiveIntegerField()),
                ('lifts_count', models.PositiveIntegerField()),
                ('fakes_count', models.PositiveIntegerField()),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itgdb_site.song')),
            ],
        ),
    ]
