# Generated by Django 5.0 on 2024-02-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itgdb_site', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chart',
            index=models.Index(fields=['steps_type'], name='itgdb_site__steps_t_777d99_idx'),
        ),
        migrations.AddIndex(
            model_name='chart',
            index=models.Index(fields=['difficulty'], name='itgdb_site__difficu_e443d0_idx'),
        ),
        migrations.AddIndex(
            model_name='chart',
            index=models.Index(fields=['meter'], name='itgdb_site__meter_7ee9bc_idx'),
        ),
    ]
