# Generated by Django 5.0 on 2024-03-23 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itgdb_site', '0003_packcategory_pack_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='packcategory',
            name='abbr',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='packcategory',
            name='color',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
