# Generated by Django 5.0 on 2024-04-20 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itgdb_site', '0004_packcategory_abbr_packcategory_color'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''CREATE TEXT SEARCH DICTIONARY simple_nostop (
                TEMPLATE = simple
            );''',
            reverse_sql='DROP TEXT SEARCH DICTIONARY simple_nostop;'
        ),
        migrations.RunSQL(
            sql='''CREATE TEXT SEARCH CONFIGURATION public.itgdb_search (
                COPY = pg_catalog.simple
            );''',
            reverse_sql='DROP TEXT SEARCH CONFIGURATION public.itgdb_search;'
        ),
        migrations.RunSQL(
            sql='''ALTER TEXT SEARCH CONFIGURATION public.itgdb_search
                ALTER MAPPING FOR asciiword, asciihword, hword_asciipart, hword, hword_part, word
                WITH simple_nostop;''',
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
