# Generated by Django 5.0 on 2024-05-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itgdb_site', '0005_search_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='links',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.CheckConstraint(check=models.Q(('pack__isnull', True), ('links__exact', ''), _connector='OR'), name='links_only_for_singles'),
        ),
    ]
