# Generated by Django 5.0 on 2024-07-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itgdb_site', '0007_alter_song_artist_alter_song_artist_translit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='upload_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pack',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pack',
            name='upload_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='has_bgchanges',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='has_fgchanges',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='upload_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chart',
            name='chart_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='chart',
            name='credit',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='chart',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
