# Generated by Django 5.0 on 2024-07-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itgdb_site', '0008_chart_upload_date_pack_author_pack_upload_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='has_attacks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='has_attacks',
            field=models.BooleanField(default=False),
        ),
    ]
