# Generated by Django 5.0 on 2024-08-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itgdb_site', '0010_alter_chart_upload_date_alter_pack_upload_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='analysis',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='has_sm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='has_ssc',
            field=models.BooleanField(default=False),
        ),
    ]
