# Generated by Django 5.0 on 2024-08-13 23:11

from django.db import migrations


def move_density_data_to_analysis(apps, schema_editor):
    Chart = apps.get_model('itgdb_site', 'Chart')
    for chart in Chart.objects.all():
        chart.analysis['density_graph'] = chart.density_graph
        chart.save()

def move_density_data_from_analysis(apps, schema_editor):
    Chart = apps.get_model('itgdb_site', 'Chart')
    for chart in Chart.objects.all():
        chart.density_graph = chart.analysis['density_graph']
        chart.save()


class Migration(migrations.Migration):

    dependencies = [
        ('itgdb_site', '0011_chart_analysis_song_has_sm_song_has_ssc'),
    ]

    operations = [
        migrations.RunPython(
            move_density_data_to_analysis, move_density_data_from_analysis
        )
    ]
