# Generated by Django 5.0 on 2024-08-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itgdb_site', '0012_move_density_data_to_analysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='density_graph',
        ),
    ]
