# Generated by Django 5.0 on 2024-08-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itgdb_site', '0017_alter_song_artist_alter_song_artist_translit_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chart',
            constraint=models.UniqueConstraint(fields=('song', 'steps_type', 'difficulty', 'description'), name='cannot_have_multiple_charts_of_same_diff_slot_and_desc'),
        ),
        migrations.AddConstraint(
            model_name='chart',
            constraint=models.UniqueConstraint(condition=models.Q(('difficulty', 5), _negated=True), fields=('song', 'steps_type', 'difficulty'), name='cannot_have_multiple_non_edit_charts_in_same_diff_slot'),
        ),
    ]
