# Generated by Django 5.0 on 2024-09-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itgdb_site', '0018_chart_cannot_have_multiple_charts_of_same_diff_slot_and_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='description',
            field=models.CharField(blank=True, default='', max_length=511),
        ),
    ]
