# Generated by Django 5.1.4 on 2025-06-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itgdb_site', '0020_chart_release_date_year_only_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='pack_ini',
            field=models.TextField(blank=True),
        ),
    ]
