# Generated by Django 5.1.4 on 2026-07-23 05:55

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itgdb_site', '0021_pack_pack_ini'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chart',
            index=models.Index(fields=['release_date'], name='itgdb_site__release_1603aa_idx'),
        ),
        migrations.AddIndex(
            model_name='chart',
            index=models.Index(fields=['chart_hash'], name='itgdb_site__chart_h_c3913d_idx'),
        ),
        migrations.AddIndex(
            model_name='chart',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('credit', 'description', 'chart_name', config='public.itgdb_search'), name='chart_description_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(django.db.models.functions.text.Upper('title'), django.db.models.functions.text.Upper('subtitle'), name='song_upper_title_subtitle_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['release_date'], name='itgdb_site__release_188e80_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['upload_date'], name='itgdb_site__upload__16f305_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['chart_length'], name='itgdb_site__chart_l_a773ad_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('title', 'subtitle', 'title_translit', 'subtitle_translit', 'artist', 'artist_translit', config='public.itgdb_search'), name='song_title_artist_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('title', 'subtitle', 'title_translit', 'subtitle_translit', config='public.itgdb_search'), name='song_title_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('artist', 'artist_translit', config='public.itgdb_search'), name='song_artist_gin_idx'),
        ),
    ]
